version: '3.8'

services:
  calculator_app:
    build: .
    container_name: calculator_app
    ports:
      - "8180:8180"

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    ports:
      - "8081:8081"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - calculator_app
